name: 'Deploy'
description: 'Deploys the code to an environment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.environment }}
    - ${{ inputs.slack_webhook }}
inputs:
  name:
    description: 'Name of the app (eg. Broadband Plans)'
    required: true
  namespace:
    description: 'Kubernetes namespace to deploy to'
    required: true
  environment:
    description: 'Environment to deploy in (eg. staging, production)'
    required: true
  slack_webhook:
    description: 'Slack webhook to post notifications'
    required: true
