#!/usr/bin/env bash

set -eo pipefail

################################################################################
# Set Variables
################################################################################

APP="${GITHUB_REPOSITORY/switcher-ie\//}"
TAG=$(git rev-parse --short=7 HEAD)

################################################################################
# Set Path
################################################################################

export PATH="$PATH:/bin"

################################################################################
# Extract PR Number from GitHub Event Context
################################################################################

if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
  GITHUB_PR_NUMBER=$(jq '.pull_request.number' "$GITHUB_EVENT_PATH")
  export GITHUB_PR_NUMBER
fi

################################################################################
# Login to GitHub Container Registry
################################################################################

echo "$INPUT_GITHUB_CONTAINER_REGISTRY_TOKEN" | docker login ghcr.io -u switcher-ie-deploy --password-stdin

################################################################################
# Build Image
################################################################################

export DOCKER_BUILDKIT=1
export MASTER_CACHE_TAG="ghcr.io/switcher-ie/$APP:master.cache"
export PR_CACHE_TAG="ghcr.io/switcher-ie/$APP:GH-PR-$GITHUB_PR_NUMBER.cache"

build "${TAG}" "${GITHUB_SHA}" "${APP}"

################################################################################
# Push Image
################################################################################

push "${TAG}" "${APP}"
